AWSTemplateFormatVersion: '2010-09-09'
Description: 'A Serverless App that receives the HackerOne Webhook payload, reformats it to ASFF, and forwards it to AWS Security Hub'
Outputs:
  SecurityHubWebhookReceiverApiUrl:
    Description: URL of your API endpoint to use as a HackerOne Webhook target
    Value:
      Fn::Sub: https://${SecurityHubWebhookReceiverApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/aws-hackerone-findings

Resources:
  SecurityHubWebhookReceiverApiGateway:
    Properties:
      DefinitionBody:
        info:
          description: API endpoint for invoking SecurityHubForwarderFunction
          title:
            Ref: AWS::StackName
          version: 1.0.0
        paths:
          /findings:
            post:
              consumes:
              - application/json
              produces:
              - application/json
              responses: {}
              security:
              - sigv4: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                requestParameters:
                  integration.request.header.X-Amz-Invocation-Type: '''RequestResponse'''
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SecurityHubWebhookReceiverFunction.Arn}/invocations
        securityDefinitions:
          sigv4:
            in: header
            name: Authorization
            type: apiKey
            x-amazon-apigateway-authtype: awsSigv4
        swagger: '2.0'
      EndpointConfiguration: EDGE
      StageName: prod
    Type: AWS::Serverless::Api
  SecurityHubWebhookReceiverFunction:
    Properties:
      CodeUri: ../src/
      Events:
        Api1:
          Properties:
            Method: POST
            Path: /findings
            RestApiId:
              Ref: SecurityHubWebhookReceiverApiGateway
          Type: Api
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Policies:
      - Statement:
        - Action:
          - securityhub:BatchImportFindings
          Effect: Allow
          Resource: arn:aws:securityhub:*:*:*
          Sid: SecurityHubImportFindingsPolicy
      Runtime: python3.7
      Timeout: 300
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
