AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A Serverless App that receives the HackerOne Webhook payload, reformats it to ASFF, and forwards it to AWS Security Hub.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HackerOneForwarderApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration: EDGE
      DefinitionBody:
        swagger: "2.0"
        info:
          title:
            Ref: AWS::StackName
          description: API endpoint for invoking HackerOneForwarderFunction
          version: 1.0.0
        paths:
          /aws-hackerone-findings:
            post:
              responses:
                "200":
                  description: "200 response"
                  content: {}
              x-amazon-apigateway-integration:
                type: "aws"
                httpMethod: "POST"
                uri: 
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HackerOneForwarderFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"

  HackerOneForwarderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies: 
      - Statement:
        - Action:
          - securityhub:BatchImportFindings
          Effect: Allow
          Resource: arn:aws:securityhub:*:*:*
          Sid: SecurityHubImportFindingsPolicy
      CodeUri: hackerone_forwarder/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HackerOneForward:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /aws-hackerone-findings
            Method: POST
            RestApiId:
              Ref: HackerOneForwarderApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HackerOneForwarderUrl:
    Description: "API Gateway endpoint URL for Prod stage for HackerOne Forwarder function"
    Value: !Sub "https://${HackerOneForwarderApi}.execute-api.${AWS::Region}.amazonaws.com/prod/aws-hackerone-findings/"
  HackerOneForwarderFunction:
    Description: "HackerOne Forwarder Lambda Function ARN"
    Value: !GetAtt HackerOneForwarderFunction.Arn
  HackerOneForwarderFunctionIamRole:
    Description: "Implicit IAM Role created for HackerOne Forwarder function"
    Value: !GetAtt HackerOneForwarderFunctionRole.Arn
